domain_path: C:\Users\cloud\OneDrive\_Arty_Spartan_7\Projects\AS7341-ARTYS7-50-I2C-MAIN\AS7341_plat\export\AS7341_plat\sw\standalone_microblaze_0
app_src_dir: C:\Xilinx\Vitis\2023.2\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
