# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.srcs/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/AS7341_axi_smc_0.xci
# IP: The module: 'AS7341_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/bd_bf6e.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_0/bd_bf6e_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_1/bd_bf6e_psr0_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_2/bd_bf6e_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_3/bd_bf6e_psr_aclk1_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_4/bd_bf6e_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_5/bd_bf6e_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_6/bd_bf6e_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_7/bd_bf6e_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_8/bd_bf6e_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_9/bd_bf6e_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_10/bd_bf6e_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_11/bd_bf6e_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_12/bd_bf6e_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_13/bd_bf6e_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_14/bd_bf6e_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_15/bd_bf6e_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_16/bd_bf6e_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_17/bd_bf6e_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_18/bd_bf6e_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_19/bd_bf6e_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_20/bd_bf6e_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_21/bd_bf6e_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_22/bd_bf6e_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_23/bd_bf6e_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_24/bd_bf6e_s02mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_25/bd_bf6e_s02tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_26/bd_bf6e_s02sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_27/bd_bf6e_s02a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_28/bd_bf6e_sarn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_29/bd_bf6e_srn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_30/bd_bf6e_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_31/bd_bf6e_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_32/bd_bf6e_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_33/bd_bf6e_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_34/bd_bf6e_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_35/bd_bf6e_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_36/bd_bf6e_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_37/bd_bf6e_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_38/bd_bf6e_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_39/bd_bf6e_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_40/bd_bf6e_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_41/bd_bf6e_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_42/bd_bf6e_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_43/bd_bf6e_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_44/bd_bf6e_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_45/bd_bf6e_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_46/bd_bf6e_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_47/bd_bf6e_m02s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_48/bd_bf6e_m02arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_49/bd_bf6e_m02rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_50/bd_bf6e_m02awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_51/bd_bf6e_m02wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_52/bd_bf6e_m02bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_53/bd_bf6e_m02e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_54/bd_bf6e_m03s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_55/bd_bf6e_m03arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_56/bd_bf6e_m03rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_57/bd_bf6e_m03awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_58/bd_bf6e_m03wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_59/bd_bf6e_m03bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_60/bd_bf6e_m03e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_61/bd_bf6e_m04s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_62/bd_bf6e_m04arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_63/bd_bf6e_m04rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_64/bd_bf6e_m04awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_65/bd_bf6e_m04wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_66/bd_bf6e_m04bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_67/bd_bf6e_m04e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_1/bd_bf6e_psr0_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_1/bd_bf6e_psr0_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_2/bd_bf6e_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_2/bd_bf6e_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_3/bd_bf6e_psr_aclk1_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_3/bd_bf6e_psr_aclk1_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_4/bd_bf6e_arsw_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_5/bd_bf6e_rsw_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_6/bd_bf6e_awsw_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_7/bd_bf6e_wsw_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_8/bd_bf6e_bsw_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_12/bd_bf6e_s00a2s_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_13/bd_bf6e_sarn_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_13/bd_bf6e_sarn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_14/bd_bf6e_srn_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_14/bd_bf6e_srn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_15/bd_bf6e_sawn_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_15/bd_bf6e_sawn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_16/bd_bf6e_swn_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_16/bd_bf6e_swn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_17/bd_bf6e_sbn_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_17/bd_bf6e_sbn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_21/bd_bf6e_s01a2s_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_22/bd_bf6e_sarn_1_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_22/bd_bf6e_sarn_1_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_23/bd_bf6e_srn_1_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_23/bd_bf6e_srn_1_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_27/bd_bf6e_s02a2s_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_28/bd_bf6e_sarn_2_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_28/bd_bf6e_sarn_2_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_29/bd_bf6e_srn_2_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_29/bd_bf6e_srn_2_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_30/bd_bf6e_sawn_1_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_30/bd_bf6e_sawn_1_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_31/bd_bf6e_swn_1_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_31/bd_bf6e_swn_1_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_32/bd_bf6e_sbn_1_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_32/bd_bf6e_sbn_1_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_33/bd_bf6e_m00s2a_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_34/bd_bf6e_m00arn_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_34/bd_bf6e_m00arn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_35/bd_bf6e_m00rn_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_35/bd_bf6e_m00rn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_36/bd_bf6e_m00awn_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_36/bd_bf6e_m00awn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_37/bd_bf6e_m00wn_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_37/bd_bf6e_m00wn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_38/bd_bf6e_m00bn_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_38/bd_bf6e_m00bn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_40/bd_bf6e_m01s2a_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_41/bd_bf6e_m01arn_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_41/bd_bf6e_m01arn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_42/bd_bf6e_m01rn_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_42/bd_bf6e_m01rn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_43/bd_bf6e_m01awn_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_43/bd_bf6e_m01awn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_44/bd_bf6e_m01wn_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_44/bd_bf6e_m01wn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_45/bd_bf6e_m01bn_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_45/bd_bf6e_m01bn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_47/bd_bf6e_m02s2a_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_48/bd_bf6e_m02arn_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_48/bd_bf6e_m02arn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_49/bd_bf6e_m02rn_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_49/bd_bf6e_m02rn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_50/bd_bf6e_m02awn_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_50/bd_bf6e_m02awn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_51/bd_bf6e_m02wn_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_51/bd_bf6e_m02wn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_52/bd_bf6e_m02bn_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_52/bd_bf6e_m02bn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_54/bd_bf6e_m03s2a_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_55/bd_bf6e_m03arn_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_55/bd_bf6e_m03arn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_56/bd_bf6e_m03rn_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_56/bd_bf6e_m03rn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_57/bd_bf6e_m03awn_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_57/bd_bf6e_m03awn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_58/bd_bf6e_m03wn_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_58/bd_bf6e_m03wn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_59/bd_bf6e_m03bn_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_59/bd_bf6e_m03bn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_61/bd_bf6e_m04s2a_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_62/bd_bf6e_m04arn_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_62/bd_bf6e_m04arn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_63/bd_bf6e_m04rn_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_63/bd_bf6e_m04rn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_64/bd_bf6e_m04awn_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_64/bd_bf6e_m04awn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_65/bd_bf6e_m04wn_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_65/bd_bf6e_m04wn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_66/bd_bf6e_m04bn_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_66/bd_bf6e_m04bn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AS7341_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'AS7341_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.srcs/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/AS7341_axi_smc_0.xci
# IP: The module: 'AS7341_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/bd_bf6e.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_0/bd_bf6e_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_1/bd_bf6e_psr0_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_2/bd_bf6e_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_3/bd_bf6e_psr_aclk1_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_4/bd_bf6e_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_5/bd_bf6e_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_6/bd_bf6e_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_7/bd_bf6e_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_8/bd_bf6e_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_9/bd_bf6e_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_10/bd_bf6e_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_11/bd_bf6e_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_12/bd_bf6e_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_13/bd_bf6e_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_14/bd_bf6e_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_15/bd_bf6e_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_16/bd_bf6e_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_17/bd_bf6e_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_18/bd_bf6e_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_19/bd_bf6e_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_20/bd_bf6e_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_21/bd_bf6e_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_22/bd_bf6e_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_23/bd_bf6e_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_24/bd_bf6e_s02mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_25/bd_bf6e_s02tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_26/bd_bf6e_s02sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_27/bd_bf6e_s02a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_28/bd_bf6e_sarn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_29/bd_bf6e_srn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_30/bd_bf6e_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_31/bd_bf6e_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_32/bd_bf6e_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_33/bd_bf6e_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_34/bd_bf6e_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_35/bd_bf6e_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_36/bd_bf6e_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_37/bd_bf6e_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_38/bd_bf6e_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_39/bd_bf6e_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_40/bd_bf6e_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_41/bd_bf6e_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_42/bd_bf6e_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_43/bd_bf6e_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_44/bd_bf6e_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_45/bd_bf6e_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_46/bd_bf6e_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_47/bd_bf6e_m02s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_48/bd_bf6e_m02arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_49/bd_bf6e_m02rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_50/bd_bf6e_m02awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_51/bd_bf6e_m02wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_52/bd_bf6e_m02bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_53/bd_bf6e_m02e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_54/bd_bf6e_m03s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_55/bd_bf6e_m03arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_56/bd_bf6e_m03rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_57/bd_bf6e_m03awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_58/bd_bf6e_m03wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_59/bd_bf6e_m03bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_60/bd_bf6e_m03e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_61/bd_bf6e_m04s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_62/bd_bf6e_m04arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_63/bd_bf6e_m04rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_64/bd_bf6e_m04awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_65/bd_bf6e_m04wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_66/bd_bf6e_m04bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_67/bd_bf6e_m04e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_1/bd_bf6e_psr0_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_1/bd_bf6e_psr0_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_2/bd_bf6e_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_2/bd_bf6e_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_3/bd_bf6e_psr_aclk1_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_3/bd_bf6e_psr_aclk1_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_4/bd_bf6e_arsw_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_5/bd_bf6e_rsw_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_6/bd_bf6e_awsw_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_7/bd_bf6e_wsw_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_8/bd_bf6e_bsw_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_12/bd_bf6e_s00a2s_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_13/bd_bf6e_sarn_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_13/bd_bf6e_sarn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_14/bd_bf6e_srn_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_14/bd_bf6e_srn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_15/bd_bf6e_sawn_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_15/bd_bf6e_sawn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_16/bd_bf6e_swn_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_16/bd_bf6e_swn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_17/bd_bf6e_sbn_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_17/bd_bf6e_sbn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_21/bd_bf6e_s01a2s_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_22/bd_bf6e_sarn_1_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_22/bd_bf6e_sarn_1_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_23/bd_bf6e_srn_1_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_23/bd_bf6e_srn_1_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_27/bd_bf6e_s02a2s_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_28/bd_bf6e_sarn_2_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_28/bd_bf6e_sarn_2_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_29/bd_bf6e_srn_2_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_29/bd_bf6e_srn_2_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_30/bd_bf6e_sawn_1_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_30/bd_bf6e_sawn_1_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_31/bd_bf6e_swn_1_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_31/bd_bf6e_swn_1_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_32/bd_bf6e_sbn_1_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_32/bd_bf6e_sbn_1_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_33/bd_bf6e_m00s2a_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_34/bd_bf6e_m00arn_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_34/bd_bf6e_m00arn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_35/bd_bf6e_m00rn_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_35/bd_bf6e_m00rn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_36/bd_bf6e_m00awn_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_36/bd_bf6e_m00awn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_37/bd_bf6e_m00wn_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_37/bd_bf6e_m00wn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_38/bd_bf6e_m00bn_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_38/bd_bf6e_m00bn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_40/bd_bf6e_m01s2a_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_41/bd_bf6e_m01arn_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_41/bd_bf6e_m01arn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_42/bd_bf6e_m01rn_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_42/bd_bf6e_m01rn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_43/bd_bf6e_m01awn_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_43/bd_bf6e_m01awn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_44/bd_bf6e_m01wn_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_44/bd_bf6e_m01wn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_45/bd_bf6e_m01bn_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_45/bd_bf6e_m01bn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_47/bd_bf6e_m02s2a_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_48/bd_bf6e_m02arn_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_48/bd_bf6e_m02arn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_49/bd_bf6e_m02rn_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_49/bd_bf6e_m02rn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_50/bd_bf6e_m02awn_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_50/bd_bf6e_m02awn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_51/bd_bf6e_m02wn_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_51/bd_bf6e_m02wn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_52/bd_bf6e_m02bn_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_52/bd_bf6e_m02bn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_54/bd_bf6e_m03s2a_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_55/bd_bf6e_m03arn_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_55/bd_bf6e_m03arn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_56/bd_bf6e_m03rn_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_56/bd_bf6e_m03rn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_57/bd_bf6e_m03awn_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_57/bd_bf6e_m03awn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_58/bd_bf6e_m03wn_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_58/bd_bf6e_m03wn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_59/bd_bf6e_m03bn_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_59/bd_bf6e_m03bn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_61/bd_bf6e_m04s2a_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_62/bd_bf6e_m04arn_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_62/bd_bf6e_m04arn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_63/bd_bf6e_m04rn_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_63/bd_bf6e_m04rn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_64/bd_bf6e_m04awn_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_64/bd_bf6e_m04awn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_65/bd_bf6e_m04wn_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_65/bd_bf6e_m04wn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_66/bd_bf6e_m04bn_0_ooc.xdc

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/bd_0/ip/ip_66/bd_bf6e_m04bn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AS7341_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/ip/AS7341_axi_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'AS7341_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
