# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/digilent-xdc-master/Arty-S7-50-Master.xdc

# Block Designs: bd/AS7341/AS7341.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AS7341 || ORIG_REF_NAME==AS7341} -quiet] -quiet

# IP: bd/AS7341/ip/AS7341_mig_7series_0_0/AS7341_mig_7series_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AS7341_mig_7series_0_0 || ORIG_REF_NAME==AS7341_mig_7series_0_0} -quiet] -quiet

# IP: bd/AS7341/ip/AS7341_xlconstant_0_0/AS7341_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AS7341_xlconstant_0_0 || ORIG_REF_NAME==AS7341_xlconstant_0_0} -quiet] -quiet

# IP: bd/AS7341/ip/AS7341_clk_wiz_0_0/AS7341_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AS7341_clk_wiz_0_0 || ORIG_REF_NAME==AS7341_clk_wiz_0_0} -quiet] -quiet

# IP: bd/AS7341/ip/AS7341_microblaze_0_0/AS7341_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AS7341_microblaze_0_0 || ORIG_REF_NAME==AS7341_microblaze_0_0} -quiet] -quiet

# IP: bd/AS7341/ip/AS7341_dlmb_v10_0/AS7341_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AS7341_dlmb_v10_0 || ORIG_REF_NAME==AS7341_dlmb_v10_0} -quiet] -quiet

# IP: bd/AS7341/ip/AS7341_ilmb_v10_0/AS7341_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AS7341_ilmb_v10_0 || ORIG_REF_NAME==AS7341_ilmb_v10_0} -quiet] -quiet

# IP: bd/AS7341/ip/AS7341_dlmb_bram_if_cntlr_0/AS7341_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AS7341_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==AS7341_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/AS7341/ip/AS7341_ilmb_bram_if_cntlr_0/AS7341_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AS7341_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==AS7341_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/AS7341/ip/AS7341_lmb_bram_0/AS7341_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AS7341_lmb_bram_0 || ORIG_REF_NAME==AS7341_lmb_bram_0} -quiet] -quiet

# IP: bd/AS7341/ip/AS7341_mdm_1_0/AS7341_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AS7341_mdm_1_0 || ORIG_REF_NAME==AS7341_mdm_1_0} -quiet] -quiet

# IP: bd/AS7341/ip/AS7341_rst_clk_wiz_0_100M_0/AS7341_rst_clk_wiz_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AS7341_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==AS7341_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/AS7341/ip/AS7341_axi_smc_0/AS7341_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AS7341_axi_smc_0 || ORIG_REF_NAME==AS7341_axi_smc_0} -quiet] -quiet

# IP: bd/AS7341/ip/AS7341_rst_mig_7series_0_81M_0/AS7341_rst_mig_7series_0_81M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AS7341_rst_mig_7series_0_81M_0 || ORIG_REF_NAME==AS7341_rst_mig_7series_0_81M_0} -quiet] -quiet

# IP: bd/AS7341/ip/AS7341_axi_uartlite_0_0/AS7341_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AS7341_axi_uartlite_0_0 || ORIG_REF_NAME==AS7341_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/AS7341/ip/AS7341_axi_quad_spi_0_0/AS7341_axi_quad_spi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AS7341_axi_quad_spi_0_0 || ORIG_REF_NAME==AS7341_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/AS7341/ip/AS7341_axi_iic_0_0/AS7341_axi_iic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AS7341_axi_iic_0_0 || ORIG_REF_NAME==AS7341_axi_iic_0_0} -quiet] -quiet

# IP: bd/AS7341/ip/AS7341_axi_gpio_0_0/AS7341_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AS7341_axi_gpio_0_0 || ORIG_REF_NAME==AS7341_axi_gpio_0_0} -quiet] -quiet

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/AS7341-ARTYS7-50-I2C-MAIN/AS7341-ARTYS7-50-I2C-MAIN.gen/sources_1/bd/AS7341/AS7341_ooc.xdc
